### ISSUE TITLE
Rust Rewrite

### ISSUE THREAD

**Issue by auguwu** [auguwu/hazel#9]
Due to some issues with Ktor and Java's InputStreams, I decided to rewrite it in Rust for the stable release of **hazel**.

Why Rust? - Because, why not? I done HTTP servers with it before! :D

## Roadmap
- [ ] Implement **remi** libraries in Rust (under `lib/remi`)
   - [ ] **Filesystem**
   - [ ] **S3**

- [ ] Implement common utilities and types (under `lib/types`)
- [ ] Implement CLI (under `cli`)
- [ ] Implement server (under `server`)
    - [ ] Routing
    - [ ] File requests
